---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project

# To run
#   * Ensure Docker is installed
#   * Start the tutorial stack using
#     'docker-compose -f ./egeria-tutorial.yaml up'
#   * starts 3 egeria serves, kafka, zookeeper & jupyter notebook
#   * Go to notebook at http://localhost:18888
#
# See the following link for more info on volumes & why we need to use root:
#   https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/

version: '3.7'

services:

    zookeeper:
        image: 'bitnami/zookeeper:latest'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - '12181:2181'
        networks:
            - cocopharma

    kafka:
        depends_on:
            - zookeeper
        image: 'bitnami/kafka:latest'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=180000
        ports:
            - '19092:9092'
        networks:
            - cocopharma

    notebook:
        image: '${egeria_repo}/jupyter:${egeria_version}'
        environment:
            - JUPYTER_ENABLE_LAB=yes
            - corePlatformURL=http://core:8080
            - dataLakePlatformURL=http://datalake:8080
            - devPlatformURL=http://dev:8080
            - ctsPlatformURL=http://dev:8080
            - factoryPlatformURL=http://factory:8080
            - eventBusURLroot=kafka:9092
            - uiExternalURL=https://localhost:18443
        command: start.sh jupyter lab --LabApp.token='' --NotebookApp.iopub_data_rate_limit=1.0e10
        ports:
            - '18888:8888'
        depends_on:
            - kafka
            - core
            - dev
            - datalake
            - factory
        networks:
            - cocopharma
        user: root

    core:
        depends_on:
            - kafka
        image: '${egeria_repo}/egeria:${egeria_version}'
        ports:
            - '18080:8080'
        networks:
            - cocopharma

    datalake:
        depends_on:
            - kafka
        image: '${egeria_repo}/egeria:${egeria_version}'
        ports:
            - '18081:8080'
        networks:
            - cocopharma

    dev:
        depends_on:
            - kafka
        image: '${egeria_repo}/egeria:${egeria_version}'
        ports:
            - '18082:8080'
        networks:
            - cocopharma

    factory:
        depends_on:
            - kafka
        image: '${egeria_repo}/egeria:${egeria_version}'
        ports:
            - '18083:8080'
        networks:
            - cocopharma

    ui:
        depends_on:
            - datalake
        image: '${egeria_repo}/egeria:${egeria_version}'
        command: /bin/bash -c "java -jar /opt/egeria/user-interface/ui-chassis-spring-${egeria_version}.jar"
        environment:
            - OMAS_SERVER_URL=http://datalake:8080
            - OMAS_SERVER_NAME=cocoMDS4
            - OPEN_LINEAGE_SERVER_URL=http://datalake:8080
            - OPEN_LINEAGE_SERVER_NAME=open-lineage
            - OPEN_LINEAGE_GRAPH_SOURCE=MAIN
        ports:
            - '18443:8443'
        networks:
            cocopharma:
networks:
    cocopharma:
